# Generated by Django 5.0.1 on 2024-01-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='slug',
            field=models.SlugField(),
        ),
    ]
