# Generated by Django 5.0.4 on 2024-12-24 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_can_be_rated_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.CreateModel(
            name='DepartmentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.position')),
            ],
            options={
                'unique_together': {('department', 'position')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='positions',
            field=models.ManyToManyField(related_name='departments', through='accounts.DepartmentPosition', to='accounts.position'),
        ),
        migrations.CreateModel(
            name='ProfileDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'unique_together': {('profile', 'department')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='departments',
            field=models.ManyToManyField(related_name='profile_departments', through='accounts.ProfileDepartment', to='accounts.department'),
        ),
        migrations.CreateModel(
            name='ProfilePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.position')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'unique_together': {('profile', 'position')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='positions',
            field=models.ManyToManyField(related_name='profile_positions', through='accounts.ProfilePosition', to='accounts.position'),
        ),
    ]
