# Generated by Django 5.0.4 on 2024-12-24 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_position_department_remove_profile_department_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profileposition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='profileposition',
            name='position',
        ),
        migrations.RemoveField(
            model_name='profileposition',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='department',
            name='positions',
        ),
        migrations.AlterField(
            model_name='position',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='ProfileDepartmentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.position')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'unique_together': {('profile', 'department', 'position')},
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='departments',
            field=models.ManyToManyField(related_name='profiles', through='accounts.ProfileDepartmentPosition', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='positions',
            field=models.ManyToManyField(related_name='profiles', through='accounts.ProfileDepartmentPosition', to='accounts.position'),
        ),
        migrations.DeleteModel(
            name='ProfileDepartment',
        ),
        migrations.DeleteModel(
            name='ProfilePosition',
        ),
    ]
