# Generated by Django 5.0.4 on 2024-12-30 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_department_slug_alter_position_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthday_dayofyear_internal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.position'),
        ),
        migrations.DeleteModel(
            name='ProfileDepartmentPosition',
        ),
    ]
