# Generated by Django 5.0.4 on 2024-12-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_positions_remove_profile_departments_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentposition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='department',
            name='positions',
            field=models.ManyToManyField(related_name='departments', through='accounts.DepartmentPosition', to='accounts.position'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.rank'),
        ),
        migrations.AddConstraint(
            model_name='departmentposition',
            constraint=models.UniqueConstraint(fields=('department', 'position'), name='unique_department_position'),
        ),
    ]
