# Generated by Django 5.0.4 on 2024-09-30 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0013_survey_success_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['created_at'], 'verbose_name': 'survey', 'verbose_name_plural': 'surveys'},
        ),
        migrations.AddField(
            model_name='useranswer',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djf_surveys.direction'),
        ),
    ]
