# Generated by Django 5.0.4 on 2024-11-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0016_alter_answer_options_alter_direction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer2',
            options={'ordering': ['-created_at'], 'verbose_name': 'answer for Question2', 'verbose_name_plural': 'Reyting javoblari'},
        ),
        migrations.AlterModelOptions(
            name='question2',
            options={'ordering': ['ordering'], 'verbose_name': 'rating question', 'verbose_name_plural': 'Reyting savollari'},
        ),
        migrations.AlterModelOptions(
            name='useranswer2',
            options={'ordering': ['-updated_at'], 'verbose_name': 'user answer for Question2', 'verbose_name_plural': 'Foydalanuvchi reyting javoblari'},
        ),
        migrations.AlterField(
            model_name='answer2',
            name='value',
            field=models.PositiveIntegerField(help_text='Reyting qiymati, masalan, 1 dan 5 gacha.', verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='choices',
            field=models.TextField(blank=True, help_text='Reytingda yulduzlar sonini aniqlash uchun, masalan: 5.', null=True, verbose_name='choices'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='type_field',
            field=models.PositiveSmallIntegerField(choices=[(9, 'Rating')], default=9, verbose_name='type of input field'),
        ),
    ]
