# Generated by Django 5.0.4 on 2024-11-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0017_alter_answer2_options_alter_question2_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer2',
            name='rated_users',
        ),
    ]
