# Generated by Django 5.0.4 on 2024-12-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0018_remove_useranswer2_rated_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text='Agar maydon turi radio, tanlanadigan yoki ko‘p variantli bo‘lsa, ajratilgan variantlarni to‘ldiringvergullar bilan. Masalan: Erkak, Ayol.', null=True, verbose_name='variantlar'),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_text',
            field=models.CharField(blank=True, help_text='Bu yerda yordam matnini kiritishingiz mumkin.', max_length=200, null=True, verbose_name='yordam matni'),
        ),
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.CharField(blank=True, help_text='Noyob kalit savol matnidan avtomatik yaratiladi. Yaratishni istasangiz, bo‘sh joyni to‘ldiring.', max_length=225, null=True, unique=True, verbose_name='kalit'),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(help_text='Savolingizni shu yerga kiriting.', max_length=500, verbose_name='Yorliq'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='So‘rovnomalar doirasida savollar tartibini belgilaydi.', verbose_name='variantlar'),
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True, help_text='Agar belgi qo‘yilsa, foydalanuvchi ushbu savolga javob berishi kerak.', verbose_name='talab qilinadi'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='choices',
            field=models.TextField(blank=True, help_text='Reytingda yulduzlar sonini aniqlash uchun, masalan: 5', null=True, verbose_name='variantlar'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='help_text',
            field=models.CharField(blank=True, help_text='Bu yerda yordam matnini kiritishingiz mumkin', max_length=200, null=True, verbose_name='yordam matni'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='key',
            field=models.CharField(blank=True, help_text='Noyob kalit savol matnidan avtomatik yaratiladi. Yaratishni istasangiz, bo‘sh joyni to‘ldiring.', max_length=225, null=True, unique=True, verbose_name='kalit'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='label',
            field=models.CharField(help_text='Savolingizni shu yerga kiriting.', max_length=500, verbose_name='yorliq'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='So‘rovnomalar doirasida savollar tartibini belgilaydi.', verbose_name='variantlar'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='required',
            field=models.BooleanField(default=True, help_text='Agar belgi qo‘yilsa, foydalanuvchi ushbu savolga javob berishi kerak.', verbose_name='talab qilinadi'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='can_anonymous_user',
            field=models.BooleanField(default=False, help_text='Agar belgi qo‘yilsa, autentifikatsiyasiz foydalanuvchi yuboradi.', verbose_name='anonim yuborish'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='deletable',
            field=models.BooleanField(default=True, help_text="Agar belgi qo‘yilmasa, foydalanuvchi yozuvni o'chira olmaydi.", verbose_name='o‘chirib tashlasa bo‘ladigan'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(default='', verbose_name='ta’rif'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='duplicate_entry',
            field=models.BooleanField(default=False, help_text='Agar belgi qo‘yilsa, foydalanuvchi qayta topshirishi mumkin.', verbose_name='bitta foydalanuvchi bir necha marta yuborish mumkin'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='editable',
            field=models.BooleanField(default=True, help_text='Agar belgi qo‘yilmasa, foydalanuvchi yozuvni tahrirlay olmaydi.', verbose_name='tahrirlanadigan'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='notification_to',
            field=models.TextField(blank=True, help_text='Xabardor qilish uchun elektron pochta manzilingizni kiriting', null=True, verbose_name='Bildirishnoma'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='private_response',
            field=models.BooleanField(default=False, help_text='Agar belgi qo‘yilsa, faqat administrator va egasi kira oladi.', verbose_name='xususiy javob'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='success_page_content',
            field=models.TextField(blank=True, help_text='Muvaffaqiyatli sahifasi shu yerda o‘zgartirishingiz mumkin. HTML sintaksisi qo‘llab-quvvatlanadi', null=True, verbose_name='Muvaffaqiyatli yakunlash sahifasi mazmuni'),
        ),
    ]
