# Generated by Django 5.0.10 on 2025-01-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0019_alter_question_choices_alter_question_help_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nomi'),
        ),
    ]
