# Generated by Django 5.0.10 on 2025-01-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0020_alter_direction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer2',
            name='value',
            field=models.PositiveIntegerField(default=5, help_text='Reyting qiymati, masalan, 1 dan 5 gacha.', verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text='Agar maydon turi radio, tanlanadigan yoki ko‘p variantli bo‘lsa, ajratilgan variantlarni to‘ldiringvergullar bilan. Masalan: Erkak, Ayol', null=True, verbose_name='variantlar'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_field',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Text'), (1, 'Number'), (2, 'Radio'), (3, 'Select'), (4, 'Multi Select'), (5, 'Text Area'), (6, 'URL'), (7, 'Email'), (8, 'Date'), (9, 'Rating')], verbose_name='kiritish maydonining turi'),
        ),
    ]
