# Generated by Django 5.0.10 on 2025-01-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0021_alter_answer2_value_alter_question_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer2',
            name='value',
            field=models.PositiveIntegerField(help_text='Reyting qiymati, masalan, 1 dan 5 gacha.', verbose_name='value'),
        ),
    ]
